name: Java CI with Maven

on: push

jobs:
  Overview:
    permissions: write-all
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: "8"
          distribution: "temurin"
          cache: maven
      - name: Check code style with CheckStyle
        run: >
          mvn -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn 
          -B checkstyle:checkstyle
        continue-on-error: true
      - name: Static analysis of source code with PMD
        run: >
          mvn -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
          -B pmd:pmd
      - name: Compile code
        run: >
          mvn -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
          -B compiler:compile
      - name: Static analysis of bytecode with Spotbugs
        run: >
          mvn -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn 
          -B spotbugs:spotbugs
      - name: Compile unit tests
        run: >
          mvn -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn 
          -B compiler:testCompile
      - name: Report Checkstyle results
        uses: jwgmeligmeyling/checkstyle-github-action@v1.2
        with:
          path: "**/checkstyle-result.xml"
          name: Code Style Issues
          title: Code Style Issues
      - name: Report PMD results
        uses: jwgmeligmeyling/pmd-github-action@v1.2
        with:
          path: "**/pmd.xml"
          name: Static Analysis Results (Source Code)
          title: Static Analysis Results (Source Code)
      - name: Report SpotBugs results
        uses: jwgmeligmeyling/spotbugs-github-action@v1.2
        with:
          path: "**/spotbugsXml.xml"
          name: Static Analysis Results (Bytecode)
          title: Static Analysis Results (Bytecode)
      - name: Run unit tests
        run: >
          mvn -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn 
          -B surefire:test
      - name: Report results of unit tests
        uses: danratinac/junit-report-annotations-action@v1
        with:
          access-token: ${{ secrets.GITHUB_TOKEN }}
          name: Unit Test Results
        if: always()
